### ISSUE TITLE
Merge including the command and timer in the output

### ISSUE THREAD

**Issue by ed-sparkes** [Antontelesh/mochawesome-merge#11]
For me the command ... 
  `  yarn marge mochawesome.json `

produces a merged json but the json also contains 

yarn run v1.15.2 before the opening {

and Done in 0.53s. after the closing } 

as a result the json is invalid and the subsequent marge command fails

Any thoughts

**Comment by Antontelesh** [comment]
This is because log outputs to the same destination as marge — stdout. Try to not use yarn/npm/other wrapper that appends to the stdout when invoking `marge`. Or use `marge` as a JavaScript module rather than CLI command.

Since mochawesome-merge is not marge I’m closing this. If you want, you can continue to discuss in comments here or create a new issue in marge’s repository.
