### ISSUE TITLE
When I use mochawesome-merge. It merge only one test

### ISSUE THREAD

**Issue by golfzaptw** [Antontelesh/mochawesome-merge#33]
Now in version 3.0.0 when used `yarn --silent mochawesome-merge cypress/results/report/*.json > cypress/results/mochawesome.json`. After that mochawesome-merge it's generate only one test

```
devDependencies
    "mocha": "^6.2.2",
    "mochawesome": "^4.1.0",
    "mochawesome-merge": "^3.0.0",
    "mochawesome-report-generator": "^4.1.0",
```
<img width="332" alt="Screen Shot 2562-12-26 at 11 51 59" src="https://user-images.githubusercontent.com/21608972/71458605-22e2e080-27d6-11ea-8306-44ce35854942.png">

**Comment by Antontelesh** [comment]
Thank you, @golfzaptw.

@ojizero, do you know what could cause this?

**Comment by golfzaptw** [comment]
@ojizero I can explain it to you. From the image, I should have 3 test cases. But after merge report, it shows 1 test case
<img width="1299" alt="Screen Shot 2562-12-26 at 14 32 57" src="https://user-images.githubusercontent.com/21608972/71464692-eff81700-27ec-11ea-865f-ae85d95833cf.png">

**Comment by Antontelesh** [comment]
I just reproduced this in `mochawesome-merge` repo against test fixtures.
Looks like glob is performing single file search for some reason. Investigating this issue

**Comment by Antontelesh** [comment]
The glob pattern seems to be incorrectly passed from CLI argument to the script

**Comment by Antontelesh** [comment]
I got the problem. It seems like unix is trying to perform its own glob search before `yargs` start parsing the arguments. So wrapping the argument with quotes solves the problem.

I think, if we want to keep the glob as a positional argument, we will have to rely on unix doing things for us. An option would be to move it to a regular argument like this:

```
mochawesome-merge --src cypress/results/report/*.json > cypress/results/mochawesome.json
```

@ojizero / @golfzaptw what do you guys think about it? Which option would you choose?

**Comment by Antontelesh** [comment]
Tried to make it as a regular option, bash still unwraps the glob into a series of paths.
I did a small investigation of how such feature is implemented in popular libraries and found that the usual pattern is:

```
command [options...] [file...]
```

which means that on unix systems the `[file...]` part is expanded by the shell, while to continue windows support libraries usually try to run the `[file...]` arguments through the `glob` or similar tools themselves.

I would propose us to implement the same pattern. Since we do not have any options except for the glob, we need to support the following format:

```
mochawesome-merge [file...]
```

And treat all arguments as glob patterns.

@ojizero / @golfzaptw, would any of you be able to make this change? If no, I can try to find the time to make it myself.

**Comment by Antontelesh** [comment]
I have created #34 to fix this. It will bump the major version again because has breaking changes.
We should have thought about releasing an alpha or something like that.

@ojizero / @golfzaptw please take a look at that PR and tell me if you have any concerns about the changes.

**Comment by ojizero** [comment]
@Antontelesh apologies I got overwhelmed today I just got to check GitHub! Hmmm I completely forgot UNIX’ behavior with regards to globs my bad as I’ve only had a Windows machine available while working in this feature!!

Just checked the PR and it LGTM!
