### ISSUE TITLE
Pattern UKStagingJsonReports/.jsons/*.json matched no report files

### ISSUE THREAD

**Issue by aswine** [Antontelesh/mochawesome-merge#87]
Error: Pattern UKStagingJsonReports/.jsons/*.json matched no report files

I have my tests running as

npx cypress run --browser chrome --headless --spec cypress/integration/uk/smoke/*.spec.js --env grepTags=@TryNow --reporter-options reportDir=UKStagingJsonReports,reportFilename=StagingTests,html=false,json=true,overwrite=false

Here I have given a folder name and the name of the json reports as per my test environment.
After the execution I have my json reports for each individual tests in the folder "UKStagingJsonReports", but the execution fails saying StagingJsonReports/.jsons/*.json matched no report files. Is there a way to override this. Also my screenshots are getting copied from the default directory to the this custom report directory. Are there ways to override this.

Error message as it is:

Read and merge jsons from "UKStagingJsonReports/.jsons"
Copy screenshots folder from "/Users/aswinedavalath/Automation_Web/c*****/cypress/screenshots" to "UKStagingJsonReports/screenshots"
An error was thrown in your plugins file while executing the handler for the 'after:run' event.

Desired behavior
User should be able to allowed to decide where to store the json reports and screenshots if the user wants to create a new folder for the same.

**Comment by aswine** [comment]
![Screenshot 2022-06-17 at 14 31 04](https://user-images.githubusercontent.com/97105695/174308667-3db50043-edfd-409a-8500-f570e133ef84.png)
![Screenshot 2022-06-16 at 09 36 43](https://user-images.githubusercontent.com/97105695/174308709-c85d1979-47f8-4cd8-b050-b93feb73eea6.png)

**Comment by Antontelesh** [comment]
@aswine are you sure this error is from `mochawesome-merge`?
Also, could you please share your command/script for merging the reports?

**Comment by aswine** [comment]
"uk:staging:merge:reports": "mochawesome-merge ./UKStagingJsonReports/*.json > UKStaging-combined-report.json && marge  --cdn=true  UKStaging-combined-report.json" 

But this command was not executed. The command which I provided in the description was the only one executed.

Reports are getting generated under the folder UKStagingJsonReports, but the error says no reports found at UKStagingJsonReports/.jsons/

I tried changing. ">" to "o" in the merge command, but didn't help

**Comment by Antontelesh** [comment]
What script/library prints the message `Read and merge jsons from "UKStagingJsonReports/.jsons"`?

`mochawesome-merge` library does not print such messages. I bet it is printed even before mochawesome-merge is executed. And since it mentions wrong directory (/.jsons/), I believe the issue is somewhere else.

Otherwise, I recommend you to place a couple of `console.log` calls within your `node_modules/mochawesome-merge` files to check what arguments were resolved to

**Comment by aswine** [comment]
![Screenshot 2022-06-18 at 14 37 10](https://user-images.githubusercontent.com/97105695/174440126-bba1d8ba-b790-4cf2-801c-82b2fc6c431e.png)

**Comment by aswine** [comment]
![mochawesome-merge-error](https://user-images.githubusercontent.com/97105695/174440290-9f5823fa-9343-4ddb-98ae-773d1dd3e5b4.png)

**Comment by Antontelesh** [comment]
Can you log what `options` resolve to [here](https://github.com/Antontelesh/mochawesome-merge/blob/265f1d9db2f9c7b4643ec7b38b8efc4a8fd437cf/lib/index.js#L81)?

My assumption is that your system unwraps your pattern to separate files before passing arguments to `mochawesome-merge`. I would recommend you to change your config so that you don’t use the `.jsons` directory.

**Comment by aswine** [comment]
![Screenshot 2022-06-20 at 09 44 03](https://user-images.githubusercontent.com/97105695/174562297-49972a15-46d7-4d15-b818-47379592e341.png)
This is a snipper from the index.js in mochawesome-merge package. 
When would the error `Pattern ${pattern} matched no report files` be thrown to the user

**Comment by aswine** [comment]
Thank you for the help. I am closing the issue as I was able to resolve this
